#+TITLE:     CV: Mahan Fathi
#+AUTHOR:    Mahan Fathi
#+EMAIL:     mahan0fathi@gmail.com


* Education
*** Montreal Institute for Learning Algorithms: M.Sc. [Sep. 2020]
#+begin_verse
University of Montreal, School of Computer Science. Advised by Prof. [[http://pierrelucbacon.com/][Pierre-Luc Bacon]].
#+end_verse
*** Sharif University of Technology [Sep. 2017. GPA: 3.88/4.0]
#+begin_verse
School of Mechanical Engineering, Dynamics and Control.
[[http://www.openthesis.org/document/view/603263_0.pdf][Bachelor Thesis]]: Nonlinear Control of a Ballbot, with Focus on Sample-Based Motion Planning Algorithms.
#+end_verse
*** NODET: High School [Jun. 2013. GPA: 19.3/20.0]
#+begin_verse
National Organization for Development of Exceptional Talents, Mathematics and Physics.
#+end_verse

-----

* Awards and Fellowships
*** Research Assistantship at Aalto University [Jun. to Sep. 2019]
#+begin_verse
AI, ML, and Game Development. Prof. [[http://perttu.info/][Perttu Hämäläinen]].
#+end_verse
*** Awarded Membership to National Elite Foundation [Aug. 2013]
*** Silver Medalist at 25th National Physics Olympiad [Sep. 2012]

-----

* Publications
*** Control of a Ballbot Using Sampling-Based Methods (1st Author)
#+begin_verse
Submitted to Scientia Iranica, published by Sharif University of Technology.
#+end_verse
*** [[https://www.civilica.com/Paper-ISME24-ISME24_657.html][Geometry Optimization of a Single-Blade Windshield Wiper]] (1st Author)
#+begin_verse
ISME2016: 24th Annual International Conference on Mechanical Engineering.
#+end_verse

-----

* Research
*** [[github:MahanFathi/Model-Based-RL][Model-Based Policy Gradients]] [Jul. to Sep. 2019]
#+begin_verse
 Motions emerge from directly back-proping into policy networks using reparam trick and physics gradients calculated in MuJoCo.
#+end_verse
*** [[github:MahanFathi/Unity2OpenSim][Unity2OpenSim]] [Jun. to Jul. 2019]
#+begin_verse
A corss-platform painless pipeline to perform Inverse Kinematics/Dynamics of OpenSim on Unity models and motions.
#+end_verse
*** Motion Mimic [Nov. 2017 to Jan. 2018]
#+begin_verse
Thanks to the readily available CMU MoCap, a bottom-half MuJoCo model of a bipedal is
able to stably and naturally walk via *Generative Adversarial Imitation Learning(TRPO)*
and stading punching motions are succesfuly mimiced for a humanoid using
*DeepMimic(PPO)* in *Unity3D(ML-Agents)*.
#+end_verse
*** Non-Holonomic Kinodynamic Motion Planning [May. 2017]
#+begin_verse
Using optimal control as a fast inverse dynamic model, a general sample-based motion planning algorithm was proposed for complex non-holonomic agents in kinodynamic spaces.
#+end_verse
*** [[http://www.openthesis.org/document/view/603263_0.pdf][Nonlinear Control of a Ballbot]]
#+begin_verse
Online motion and path planning of the highly nonlinear Rezero, using RRT and optimal control.
#+end_verse
*** [[https://www.slideshare.net/slideshow/embed_code/key/wyRKZKDDHxy1AF][Unsupervised Object Localization]] [Sep. 2018]
#+begin_verse
Extracting the deep-seated spatial information of classification networks by Guided Back-propagating most affecting neurons to the image, enables us to spot image parts corresponding to the object.
#+end_verse

-----

* Experince
*** Team Leader at [[https://cafebazaar.ir/?l=en][CafeBazaar]] [Sep. 2019 _Ongoing_]
#+begin_verse
I currently lead a team of 6 responsible for all Computer Vision problems of [[https://balad.ir/about][Balad]] , which is the biggest domestic map and navigation application of Iran, a product of the Iranian tech giant, CafeBazaar.
#+end_verse
*** Senior Data Scientist at CafeBazaar [Oct. 2018 to Sep. 2019]
#+begin_verse
I worked at Navigation team at Balad on route planning, traffic prediction, and ETA using data-driven methods. Moreover, as a computer vision scientist I was concerned with information extraction from street and aerial imagery.
#+end_verse
*** Senior Backend Developer at [[https://tapsi.ir/][TAPSI]] [May. to Oct. 2018]
#+begin_verse
I was a member of the Dispatch/Pricing team at Tap30, which is somehow the heart of any ride-hailing platform. Whenever a ride request is submitted, we are the invisible hands behind, connecting riders and drivers.
#+end_verse
*** Data Scientist at TAPSI [Feb. to May. 2018]
#+begin_verse
Among the biggest Iranian tech companies, TAP30 is a ride-hailing platform with millions of monthly active users.
#+end_verse

-----

* Projects
*** Live Traffic [Mar. 2019]
#+begin_verse
Design, implementation, optimization, deployment, maintenance, and storage of real-time user GPS data, single-handedly. The service assigns a traffic metric to map road segments, which are then used by Navigation and ETA services.
#+end_verse
*** Street Imagery Sensitive Content Censorship [Feb. 2019]
#+begin_verse
YOLOv3 is the core of this fast censor network, responsible for blurring of faces and licence plates in street images.
#+end_verse
*** [[https://blog.usejournal.com/collecting-a-nations-points-of-interest-computer-vision-to-the-rescue-41026053bdf6][Detection and Tracking of Points of Interest]] [Nov. 2018 Jan. 2019]
#+begin_verse
Trained and deployed a Mask-RCNN model for detection of the store signs. Also came up with a novel tracking algorithm to bundle up repeating billboards in subsequent images. Read about it at [[https://blog.usejournal.com/collecting-a-nations-points-of-interest-computer-vision-to-the-rescue-41026053bdf6][my personal blog]] and [[http://vrgl.ir/jBg3J][CafeBazaar tech blog]].
#+end_verse
*** [[github:MahanFathi/end2end-self-driving-car][Learning to Drive in 2 Days]] [Mar. 2019]
#+begin_verse
Inspired by the work of NVIDIA on DAVE-2, in a team of 6, at the 7th Hackathon of CafeBazaar, we collected just enough data, to train an end-to-end deep conv-net to infer steering angle for each captured image. We then came by a pipeline to connect the center camera to this module at the test time. We were able to achieve the MVP of staying in lanes and avoiding doubled-parked cars. [[https://vimeo.com/371631581][Here is a video]]!
#+end_verse
*** Location Service Rewrite [Oct. 2018]
#+begin_verse
Reducing the response time of TAP30’s main bottleneck by a crazy factor. We made heavy use of Lua and Redis.
#+end_verse
*** Semi-concurrent Dispatch Algorithm [May. 2018 Aug. 2018]
#+begin_verse
Implementation of the algorithm as the owner of the project, which resulted in a 3% rise in our finished rides according to RCTs in the first launch. To give you a sense, a percent rise in the ride fulfillment rate in a 6-month long OKR of a team would be an ambitious target.
#+end_verse

-----

* Skills
*** Computer Science
#+begin_verse
- Adept at Deep RL, reviewed many state-of-the-art projects
- Implementation of several projects in computer vision
- Nonlinear optimization, convex optimization and numerical methods
- Mostly experienced at motion generation methods
- Optimal control theory, stochastic control, and robust control
- Direct Policy Search methods and Sequential Quadratic Programming
#+end_verse
*** Programming
#+begin_verse
- Long programming experience in C++, Python, JavaScript, Lua, and Java
- TensorFlow, PyTorch/Torch, Caffe, and Keras for Deep Learning Frameworks
- MuJoCo, Unity, and Bullet for Physics + OpenGL and Blender for Graphics
- Experienced in C#, ROS, SQL, OpenGL, Redis and Spark
- Familiarity with a number of nonlinear/convex optimization packages
#+end_verse
*** Other
#+begin_verse
- Linux, Docker, Django, Node.js, L A TEX, C, \\
  Mathematica, Matlab, Simulink, Maple, etc.
- Can’t live w/o Arch, Emacs, and i3
- Expert pencil artist and acoustic guitar fanatic
#+end_verse

-----

* Coursework
*** Machine Learning
#+begin_verse
+ Berkeley CS 294
+ David Silver's UCL Course of RL
+ Stanford's CS 231n
#+end_verse
*** Control Theory and Robotics
#+begin_verse
+ Underactuated Robotics by Russ Tedrake
+ Programming for Robotics - ROS (ETH)
+ Artificial Intelligence for Robotics (Udacity)
#+end_verse
*** Robotics Related Courses from Bachelor
#+begin_verse
+ Mechanism Design (1st in class 19.8/20.0)
+ Engineering Math (1st in class 19.5/20.0)
+ Programming in C (1st in class 20.0/20.0)
+ Dynamics of Machines (3st in class 19.1/20.0)
+ Dynamics and Modeling (3st in class 19.9/20.0)
#+end_verse

-----

* Teaching
*** Mathematica Instructor [Dec. 2016]
#+begin_verse
Two-week long, additional program at Sharif University of Technology.
#+end_verse
*** Physics Olympiad Instructor [Jun. to Nov. 2014]
#+begin_verse
Introduction to Mechanics, Electrodynamics and Differential Equations.
#+end_verse

-----

* Language
*** Persian(native), English(TOEFL iBT: 110 ), and German(basic)

-----

* Interests
*** Legged Locomotion
#+begin_verse
+ Bipedal Locomotion
+ Planning via Terrain Perception
+ Agile Gaits for Quadrupeds
+ Hierarchical Planning and Control
#+end_verse
*** Autonomous Driving
*** Kinematic Character Animation
